+++
date = "2017-10-22T01:01:01+02:00"
draft = false
title = "Albania 2017"
#slug = "salt-nacl-ext-pillar"
tags = ["blog", "travel", "roadtrip", "albania", "vacation"]
+++

:source-highlighter: coderay

[.lead]
Three mens, one free week, roadtrip in Albania. Tirana, riviera, south and finally the transit Budapest.

<!--more-->


== TL;DR

We planned the trip one week before we left. Albania is known for its raw nature, mountains, and coast. 
Visiting mountains in the north part at the mid of the October was not an option as the weather is
colder and we wanted to travel light.

We got nice recommendations from "Alfi" an Albanian friend who runs a nice Caffe/Bar in Nymburk.
As many people, even we considered Albania and undeveloped country and poor people. What a surprise we soon
have found a much better picture of the region.

Albania is a nice country we finally decided to go back soon. For a fun with our families and possibly even for a north
region for mountains we were forced to skip this time.

I wrote this for a record. Some details are not mentioned. Contact me if you have questions. 
Some tips for the future visit are at the end of the article. Hope you find it useful.

== Travel

Travelers:

* Michal Peska
* Petr Michalec
* Radovan Svaty

Radovan found a nice tickets from Budapest for 23000Ft which is about 180 euro (however if you instead of buying them two months before the flight
you may get even "better" price around 40 euro for a return trip including baggage). So we have driven a car from the Czech Republic and
left the car on a Parking slot for about 20e. The other option is to fly to Corfu and take a ship.

=== Weather
Weather conditions were quite generous to us as during the day was average 24 degrees, with max 28 degrees. On the evening/night 12-15.
Usually, it starts to rain at the beginning of October, but not this time. Long pants and a jacket for a night is a good option.
(Notable to mention Albanians wear long pants and even sweater so tourists in shorts look different.)

=== Car
We booked a car before the flight at Enterprise. Unless you go to Albania to the Riviera/coastline or you know you will only stay on the main roads, don't rent a small car. Roads
are fine on main ways, but any city/smaller road you will meet pot holes or stones.
Worth to mention that for 4x4 "Suzuki Vitara" category we booked we were first offered
Fiat 500. Finally, we got Duster, but simple tires and pretty bad condition (seems like bee flooded a week).
If you want to go for mountains, dirty off-road make sure you buy the real offroad car and you have it confirmed first.
For short trips on main highways, I would by a car at the airport or Tirana so you can get a better price and you can choose
what's available from multiple companies.

Roads are moderate on main highways. We were a couple of times warned don't go out of these without a good car. It's not
dangerous, but you will lose your time. Signs get much better these days. Streets have names, roundabouts are well signed and
with GPS offline map we had no issues to navigate to the destination.

This country is amazing. The petrol stations are everywhere as frequent as small old bunkers from the 2nd world war.
In average there were always four petrol stations within 3km. Almost seems it's a family business here.

The best experience ever was food, services, and great coffee on every corner.

=== Itinerary

The itinerary was set on the way. We have had just main points. Finally, we choose to go from
Tirana to Durres first day,
then to Berat for the second,
the third day we spend mostly driving the riviera to Borsc.
Then we have moved to Saranda, Gjirokaster and finally Kruje \~30km above the Tirana.
Last day we spent in Tirana.

=== Prices

Prices were nice. In general three times cheaper or equal to the Czech Republic at finest places.
Accommodation in average 25 euro/night/room for all of us. Food is excellent and prices are more than happy, we frequently
got an appetizer just because we have made a bug lunch or dinner. 

For coffee drinkers, Albania is a dream place to visit. We frequently found Albanians understand Italian language and connection
to Italy don't end-up with watching TV shows or sharing a sea border. They love coffee and they know how to make t a good
way. We were drinking excellent coffee on every corner in every district we visited. While the avarage price was 20 Leku, 
the price in non tourists areas was just 10 Leku. And btw one of the best I have had at the airport gas station.

=== Internet

The Internet is everywhere but for some stupid reason, telco companies, has this Europe touching country (Greece, 30km to Italy and even less
to Corfu) on a list of II. zone so calls, SMS and data are not worth the price. No worry, from Borsc to south you will be
able to connect to EU cell network on Corfu.


== Places we visited

The country very conservative. You can meet grandpa's in a suit the whole day, playing chess or drinking coffee. At evening
sitting and reading in the park. Time has stopped here 100 years ago at some places.
Count you will not meet girls or laddies at night as they stay at home. 
At old cities no bars or clubs are open. Especially not at late night. 
Mens on the other has its own places to go night, drinking coffee, raki or watch football on TV together.

There is one exception "Tirana" to all of these. It's like another big city. Albanians young go to Tirana to study, meet girls
and have a fun.

== Dures

Frequent destination offered by agencies. Except the "city rush" and the bar and restaurants on the coast we have not found anything
interesting.

== Berat

On a way to there, you may fruits, etc. around the main street. Buy some, people are friendly and you will enjoy it.

Old town. Christians and Muslim part split by the river with two nice bridges. Ruins of Castle and accommodation on the tall
hill with beautiful viewpoints. Especially at night. Book your room for a night here and go out for a splendid dinner.

When we left beat we visited small vine yard XYZ.


== Riviera

On a way down, exit the main road and visit small villages. It's a great experience.
Riviera is the nice place with pure water and nice coastline. You will be driving the hills and beaches. While Vlore, Dures, and Sarrande are well-known locality. The raw nice places between Vlore and Saranda are in recent years still discovered by
NATIVES.

== Vlore

Bigger coast city, nice beach, and parks around. Next to Tirana, I would guess you may even find a nightlife here.

== Qeparo

Beach

== Borsc

Castel
Nice valley


== Piceras

Small village with an atmosphere.
Nice beach on the coast.

== Sarrande

Smaller city. Nothing to see in the center. But great accommodation/food services and check the pictures from the beach.

Close to Sarrande is a most frequently visited place for tourists. Worth to see but don't expect more than ruins.
A small museum was, however, a nice surprise. NADECH HISTORIE, Nice viewpoints. No surprise this place was favorited by Romans.

== Gjirokaster

UNESCO old town surrounded by mountains. Famous for roofs made from stone.

To Gjirokaster you will follow the big river "Vosel". The last raw and wild river in Europe.

We drove directly to "old" part. Up the hill for accommodation. You want to stay here for a day and night.

The best place to stay is Kobra or XYZ if you are here with your girlfriend or wife. Kobra is definitively best viewpoint and
nice place for dinner or coffee. But you will find many other places for a dinner with a superb atmosphere all around. 
Cheaper option to stay overnight are hostels or rooms in the old town. We did it and we liked it as it was not the "Europe"
styled but typical Albanian place.

== Kruje

As we had no free day we drove directly to Kruje. First, it's doable (a long way). Second Elbasan on the road we have not
found interesting. The other directions to the north (Korce, Mountains) would take too long.

Kruje is close to Tirana. A city on a hill. You will see Tirana and Durres on the night. 

This was the most expensive place - we stayed at Panorama hotel as we arrived late and were lazy to find something. 
I would recommend you to choose some other place here with some more local atmosphere. 

This city is unique. Worth to see even for a few hours.

Museum, Ethnological Museum, food !!

== Tirana

The main city, you already know what to expect, nothing special to see. Go out and enjoy nightlife and food.

Well while the whole country is quite conservative, regarding nightlife in Tirana it's total opposite. Young people comes
here for study and to have a fun. People live here the same as in the other Europe cities. That's good and bad at the same
time but after a week of literally quite evenings we have found the concert on the main square the perfect "dot" for our
travel.

Btw, the main square has kind of architectural anomaly as it's made inflated rather than flat.

Nice place we visited except the common sight-seeing spots was a Park and a restaurant corner close to the statute of called
"mother of Albania".

== On the next trip to Albania

- Riviera and best places we saw with Family
- Pogradec
- Shkorder
- For next "man's" trip
  - Mountains
  - Offroads
  - 2x 3day track (while one in car)
  - Rafting

== Photo gallery

TIP: Full gallery you may find on my
      https://photos.google.com/u/1/share/AF1QipOkF_YX0t3MN1YH7KoxtOijnPLqaMVQnH6wdlnLBiyJAcMieFSzAS1Q2JoFMQVR1Q?key=R0xtMm55M0lIaXhnRG5rR3Bmel9tUEh6OGdYYnVB[Google Photos].

{{< gallery dir="/media/post/2017/Albania" caption-position="none" />}}
{{< load-photoswipe >}}
